# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='Seller_Username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
