# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='Additional_Information',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='Seller_Username',
            field=models.CharField(max_length=100),
        ),
    ]
