# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='User',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
